// <auto-generated />
using CarenAll.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarenAll.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarenAll.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CarenAll.Models.Voertuigen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aanschafjaar")
                        .HasColumnType("int");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoertuigType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Voertuigen");

                    b.HasDiscriminator<string>("VoertuigType").HasValue("Voertuigen");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CarenAll.Models.Auto", b =>
                {
                    b.HasBaseType("CarenAll.Models.Voertuigen");

                    b.HasDiscriminator().HasValue("Auto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aanschafjaar = 2018,
                            Kenteken = "AB-123-CD",
                            Kleur = "Rood",
                            Merk = "Toyota",
                            Type = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            Aanschafjaar = 2019,
                            Kenteken = "EF-456-GH",
                            Kleur = "Blauw",
                            Merk = "Ford",
                            Type = "Focus"
                        },
                        new
                        {
                            Id = 3,
                            Aanschafjaar = 2020,
                            Kenteken = "IJ-789-KL",
                            Kleur = "Zwart",
                            Merk = "Volkswagen",
                            Type = "Golf"
                        },
                        new
                        {
                            Id = 4,
                            Aanschafjaar = 2017,
                            Kenteken = "MN-012-OP",
                            Kleur = "Wit",
                            Merk = "Honda",
                            Type = "Civic"
                        },
                        new
                        {
                            Id = 5,
                            Aanschafjaar = 2021,
                            Kenteken = "QR-345-ST",
                            Kleur = "Grijs",
                            Merk = "BMW",
                            Type = "3 Serie"
                        },
                        new
                        {
                            Id = 6,
                            Aanschafjaar = 2016,
                            Kenteken = "UV-678-WX",
                            Kleur = "Zilver",
                            Merk = "Audi",
                            Type = "A4"
                        },
                        new
                        {
                            Id = 7,
                            Aanschafjaar = 2022,
                            Kenteken = "YZ-901-AB",
                            Kleur = "Blauw",
                            Merk = "Mercedes",
                            Type = "C-Klasse"
                        },
                        new
                        {
                            Id = 8,
                            Aanschafjaar = 2015,
                            Kenteken = "CD-234-EF",
                            Kleur = "Groen",
                            Merk = "Nissan",
                            Type = "Qashqai"
                        },
                        new
                        {
                            Id = 9,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-567-IJ",
                            Kleur = "Rood",
                            Merk = "Peugeot",
                            Type = "208"
                        },
                        new
                        {
                            Id = 10,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Kleur = "Zwart",
                            Merk = "Renault",
                            Type = "Clio"
                        },
                        new
                        {
                            Id = 11,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-123-QR",
                            Kleur = "Wit",
                            Merk = "Hobby",
                            Type = "De Luxe"
                        },
                        new
                        {
                            Id = 12,
                            Aanschafjaar = 2018,
                            Kenteken = "ST-456-UV",
                            Kleur = "Grijs",
                            Merk = "Fendt",
                            Type = "Bianco"
                        },
                        new
                        {
                            Id = 13,
                            Aanschafjaar = 2019,
                            Kenteken = "WX-789-YZ",
                            Kleur = "Blauw",
                            Merk = "Knaus",
                            Type = "Sport"
                        },
                        new
                        {
                            Id = 14,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Kleur = "Groen",
                            Merk = "Dethleffs",
                            Type = "Camper"
                        },
                        new
                        {
                            Id = 15,
                            Aanschafjaar = 2020,
                            Kenteken = "EF-345-GH",
                            Kleur = "Zilver",
                            Merk = "Adria",
                            Type = "Altea"
                        },
                        new
                        {
                            Id = 16,
                            Aanschafjaar = 2015,
                            Kenteken = "IJ-678-KL",
                            Kleur = "Rood",
                            Merk = "Eriba",
                            Type = "Touring"
                        },
                        new
                        {
                            Id = 17,
                            Aanschafjaar = 2021,
                            Kenteken = "MN-901-OP",
                            Kleur = "Zwart",
                            Merk = "Tabbert",
                            Type = "Puccini"
                        },
                        new
                        {
                            Id = 18,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-234-ST",
                            Kleur = "Wit",
                            Merk = "Burstner",
                            Type = "Premio"
                        },
                        new
                        {
                            Id = 19,
                            Aanschafjaar = 2018,
                            Kenteken = "UV-567-WX",
                            Kleur = "Blauw",
                            Merk = "LMC",
                            Type = "Musica"
                        },
                        new
                        {
                            Id = 20,
                            Aanschafjaar = 2022,
                            Kenteken = "YZ-890-AB",
                            Kleur = "Grijs",
                            Merk = "Sprite",
                            Type = "Cruzer"
                        },
                        new
                        {
                            Id = 21,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Kleur = "Rood",
                            Merk = "Volkswagen",
                            Type = "California"
                        },
                        new
                        {
                            Id = 22,
                            Aanschafjaar = 2019,
                            Kenteken = "GH-456-IJ",
                            Kleur = "Blauw",
                            Merk = "Mercedes",
                            Type = "Marco Polo"
                        },
                        new
                        {
                            Id = 23,
                            Aanschafjaar = 2020,
                            Kenteken = "KL-789-MN",
                            Kleur = "Zwart",
                            Merk = "Ford",
                            Type = "Nugget"
                        },
                        new
                        {
                            Id = 24,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-012-QR",
                            Kleur = "Wit",
                            Merk = "Fiat",
                            Type = "Ducato"
                        },
                        new
                        {
                            Id = 25,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-345-UV",
                            Kleur = "Grijs",
                            Merk = "Citroen",
                            Type = "Jumper"
                        },
                        new
                        {
                            Id = 26,
                            Aanschafjaar = 2016,
                            Kenteken = "WX-678-YZ",
                            Kleur = "Zilver",
                            Merk = "Peugeot",
                            Type = "Boxer"
                        },
                        new
                        {
                            Id = 27,
                            Aanschafjaar = 2022,
                            Kenteken = "AB-901-CD",
                            Kleur = "Blauw",
                            Merk = "Renault",
                            Type = "Master"
                        },
                        new
                        {
                            Id = 28,
                            Aanschafjaar = 2015,
                            Kenteken = "EF-234-GH",
                            Kleur = "Groen",
                            Merk = "Iveco",
                            Type = "Daily"
                        },
                        new
                        {
                            Id = 29,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-567-KL",
                            Kleur = "Rood",
                            Merk = "Opel",
                            Type = "Movano"
                        },
                        new
                        {
                            Id = 30,
                            Aanschafjaar = 2018,
                            Kenteken = "MN-890-OP",
                            Kleur = "Zwart",
                            Merk = "Nissan",
                            Type = "NV400"
                        },
                        new
                        {
                            Id = 31,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-123-ST",
                            Kleur = "Zilver",
                            Merk = "Kia",
                            Type = "Sportage"
                        },
                        new
                        {
                            Id = 32,
                            Aanschafjaar = 2020,
                            Kenteken = "UV-456-WX",
                            Kleur = "Blauw",
                            Merk = "Hyundai",
                            Type = "Tucson"
                        },
                        new
                        {
                            Id = 33,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-789-AB",
                            Kleur = "Groen",
                            Merk = "Skoda",
                            Type = "Octavia"
                        },
                        new
                        {
                            Id = 34,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-012-EF",
                            Kleur = "Wit",
                            Merk = "Mazda",
                            Type = "3"
                        },
                        new
                        {
                            Id = 35,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-345-IJ",
                            Kleur = "Grijs",
                            Merk = "Subaru",
                            Type = "Impreza"
                        },
                        new
                        {
                            Id = 36,
                            Aanschafjaar = 2019,
                            Kenteken = "KL-678-MN",
                            Kleur = "Zwart",
                            Merk = "Suzuki",
                            Type = "Vitara"
                        },
                        new
                        {
                            Id = 37,
                            Aanschafjaar = 2020,
                            Kenteken = "OP-901-QR",
                            Kleur = "Zilver",
                            Merk = "Volvo",
                            Type = "XC60"
                        },
                        new
                        {
                            Id = 38,
                            Aanschafjaar = 2017,
                            Kenteken = "ST-234-UV",
                            Kleur = "Rood",
                            Merk = "Mitsubishi",
                            Type = "Outlander"
                        },
                        new
                        {
                            Id = 39,
                            Aanschafjaar = 2022,
                            Kenteken = "WX-567-YZ",
                            Kleur = "Groen",
                            Merk = "Jeep",
                            Type = "Wrangler"
                        },
                        new
                        {
                            Id = 40,
                            Aanschafjaar = 2021,
                            Kenteken = "YZ-890-AB",
                            Kleur = "Blauw",
                            Merk = "Land Rover",
                            Type = "Defender"
                        },
                        new
                        {
                            Id = 41,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Kleur = "Grijs",
                            Merk = "Bailey",
                            Type = "Unicorn"
                        },
                        new
                        {
                            Id = 42,
                            Aanschafjaar = 2019,
                            Kenteken = "GH-456-IJ",
                            Kleur = "Zwart",
                            Merk = "Lunar",
                            Type = "Clubman"
                        },
                        new
                        {
                            Id = 43,
                            Aanschafjaar = 2020,
                            Kenteken = "KL-789-MN",
                            Kleur = "Wit",
                            Merk = "Swift",
                            Type = "Conqueror"
                        },
                        new
                        {
                            Id = 44,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-012-QR",
                            Kleur = "Zilver",
                            Merk = "Elddis",
                            Type = "Avante"
                        },
                        new
                        {
                            Id = 45,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-345-UV",
                            Kleur = "Blauw",
                            Merk = "Compass",
                            Type = "Casita"
                        },
                        new
                        {
                            Id = 46,
                            Aanschafjaar = 2016,
                            Kenteken = "WX-678-YZ",
                            Kleur = "Groen",
                            Merk = "Coachman",
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 47,
                            Aanschafjaar = 2022,
                            Kenteken = "AB-901-CD",
                            Kleur = "Rood",
                            Merk = "Buccaneer",
                            Type = "Commodore"
                        },
                        new
                        {
                            Id = 48,
                            Aanschafjaar = 2015,
                            Kenteken = "EF-234-GH",
                            Kleur = "Zwart",
                            Merk = "Caravelair",
                            Type = "Allegra"
                        },
                        new
                        {
                            Id = 49,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-567-KL",
                            Kleur = "Wit",
                            Merk = "Sterckeman",
                            Type = "Starlett"
                        },
                        new
                        {
                            Id = 50,
                            Aanschafjaar = 2018,
                            Kenteken = "MN-890-OP",
                            Kleur = "Grijs",
                            Merk = "Tab",
                            Type = "320"
                        },
                        new
                        {
                            Id = 51,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-123-ST",
                            Kleur = "Blauw",
                            Merk = "Volkswagen",
                            Type = "Grand California"
                        },
                        new
                        {
                            Id = 52,
                            Aanschafjaar = 2020,
                            Kenteken = "UV-456-WX",
                            Kleur = "Groen",
                            Merk = "Mercedes",
                            Type = "Sprinter"
                        },
                        new
                        {
                            Id = 53,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-789-AB",
                            Kleur = "Rood",
                            Merk = "Ford",
                            Type = "Transit Custom"
                        },
                        new
                        {
                            Id = 54,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-012-EF",
                            Kleur = "Zwart",
                            Merk = "Fiat",
                            Type = "Talento"
                        },
                        new
                        {
                            Id = 55,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-345-IJ",
                            Kleur = "Wit",
                            Merk = "Citroen",
                            Type = "SpaceTourer"
                        },
                        new
                        {
                            Id = 56,
                            Aanschafjaar = 2019,
                            Kenteken = "KL-678-MN",
                            Kleur = "Grijs",
                            Merk = "Peugeot",
                            Type = "Traveller"
                        },
                        new
                        {
                            Id = 57,
                            Aanschafjaar = 2020,
                            Kenteken = "OP-901-QR",
                            Kleur = "Blauw",
                            Merk = "Renault",
                            Type = "Trafic"
                        },
                        new
                        {
                            Id = 58,
                            Aanschafjaar = 2017,
                            Kenteken = "ST-234-UV",
                            Kleur = "Groen",
                            Merk = "Iveco",
                            Type = "Daily"
                        },
                        new
                        {
                            Id = 59,
                            Aanschafjaar = 2022,
                            Kenteken = "WX-567-YZ",
                            Kleur = "Rood",
                            Merk = "Opel",
                            Type = "Vivaro"
                        },
                        new
                        {
                            Id = 60,
                            Aanschafjaar = 2021,
                            Kenteken = "YZ-890-AB",
                            Kleur = "Zwart",
                            Merk = "Nissan",
                            Type = "Primastar"
                        },
                        new
                        {
                            Id = 61,
                            Aanschafjaar = 2019,
                            Kenteken = "CD-123-EF",
                            Kleur = "Wit",
                            Merk = "Toyota",
                            Type = "Yaris"
                        },
                        new
                        {
                            Id = 62,
                            Aanschafjaar = 2020,
                            Kenteken = "GH-456-IJ",
                            Kleur = "Grijs",
                            Merk = "Ford",
                            Type = "Kuga"
                        },
                        new
                        {
                            Id = 63,
                            Aanschafjaar = 2017,
                            Kenteken = "KL-789-MN",
                            Kleur = "Blauw",
                            Merk = "Volkswagen",
                            Type = "Passat"
                        },
                        new
                        {
                            Id = 64,
                            Aanschafjaar = 2018,
                            Kenteken = "OP-012-QR",
                            Kleur = "Groen",
                            Merk = "Honda",
                            Type = "Accord"
                        },
                        new
                        {
                            Id = 65,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-345-UV",
                            Kleur = "Zilver",
                            Merk = "BMW",
                            Type = "X5"
                        },
                        new
                        {
                            Id = 66,
                            Aanschafjaar = 2019,
                            Kenteken = "WX-678-YZ",
                            Kleur = "Zwart",
                            Merk = "Audi",
                            Type = "Q7"
                        },
                        new
                        {
                            Id = 67,
                            Aanschafjaar = 2020,
                            Kenteken = "AB-901-CD",
                            Kleur = "Wit",
                            Merk = "Mercedes",
                            Type = "GLC"
                        },
                        new
                        {
                            Id = 68,
                            Aanschafjaar = 2017,
                            Kenteken = "EF-234-GH",
                            Kleur = "Grijs",
                            Merk = "Nissan",
                            Type = "Juke"
                        },
                        new
                        {
                            Id = 69,
                            Aanschafjaar = 2022,
                            Kenteken = "IJ-567-KL",
                            Kleur = "Blauw",
                            Merk = "Peugeot",
                            Type = "308"
                        },
                        new
                        {
                            Id = 70,
                            Aanschafjaar = 2021,
                            Kenteken = "MN-890-OP",
                            Kleur = "Groen",
                            Merk = "Renault",
                            Type = "Megane"
                        },
                        new
                        {
                            Id = 71,
                            Aanschafjaar = 2018,
                            Kenteken = "QR-123-ST",
                            Kleur = "Rood",
                            Merk = "Tabbert",
                            Type = "Rossini"
                        },
                        new
                        {
                            Id = 72,
                            Aanschafjaar = 2019,
                            Kenteken = "UV-456-WX",
                            Kleur = "Zwart",
                            Merk = "Dethleffs",
                            Type = "Beduin"
                        },
                        new
                        {
                            Id = 73,
                            Aanschafjaar = 2020,
                            Kenteken = "YZ-789-AB",
                            Kleur = "Wit",
                            Merk = "Fendt",
                            Type = "Tendenza"
                        },
                        new
                        {
                            Id = 74,
                            Aanschafjaar = 2017,
                            Kenteken = "CD-012-EF",
                            Kleur = "Zilver",
                            Merk = "Knaus",
                            Type = "Sudwind"
                        },
                        new
                        {
                            Id = 75,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-345-IJ",
                            Kleur = "Blauw",
                            Merk = "Hobby",
                            Type = "Excellent"
                        },
                        new
                        {
                            Id = 76,
                            Aanschafjaar = 2016,
                            Kenteken = "KL-678-MN",
                            Kleur = "Groen",
                            Merk = "Adria",
                            Type = "Action"
                        },
                        new
                        {
                            Id = 77,
                            Aanschafjaar = 2022,
                            Kenteken = "OP-901-QR",
                            Kleur = "Rood",
                            Merk = "Eriba",
                            Type = "Feeling"
                        },
                        new
                        {
                            Id = 78,
                            Aanschafjaar = 2015,
                            Kenteken = "ST-234-UV",
                            Kleur = "Zwart",
                            Merk = "Burstner",
                            Type = "Averso"
                        },
                        new
                        {
                            Id = 79,
                            Aanschafjaar = 2021,
                            Kenteken = "WX-567-YZ",
                            Kleur = "Wit",
                            Merk = "LMC",
                            Type = "Vivo"
                        },
                        new
                        {
                            Id = 80,
                            Aanschafjaar = 2018,
                            Kenteken = "YZ-890-AB",
                            Kleur = "Grijs",
                            Merk = "Sprite",
                            Type = "Major"
                        },
                        new
                        {
                            Id = 81,
                            Aanschafjaar = 2019,
                            Kenteken = "CD-123-EF",
                            Kleur = "Zwart",
                            Merk = "Volkswagen",
                            Type = "Multivan"
                        },
                        new
                        {
                            Id = 82,
                            Aanschafjaar = 2020,
                            Kenteken = "GH-456-IJ",
                            Kleur = "Wit",
                            Merk = "Mercedes",
                            Type = "Vito"
                        },
                        new
                        {
                            Id = 83,
                            Aanschafjaar = 2017,
                            Kenteken = "KL-789-MN",
                            Kleur = "Grijs",
                            Merk = "Ford",
                            Type = "Custom"
                        },
                        new
                        {
                            Id = 84,
                            Aanschafjaar = 2018,
                            Kenteken = "OP-012-QR",
                            Kleur = "Blauw",
                            Merk = "Fiat",
                            Type = "Scudo"
                        },
                        new
                        {
                            Id = 85,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-345-UV",
                            Kleur = "Groen",
                            Merk = "Citroen",
                            Type = "Berlingo"
                        },
                        new
                        {
                            Id = 86,
                            Aanschafjaar = 2019,
                            Kenteken = "WX-678-YZ",
                            Kleur = "Rood",
                            Merk = "Peugeot",
                            Type = "Partner"
                        },
                        new
                        {
                            Id = 87,
                            Aanschafjaar = 2020,
                            Kenteken = "AB-901-CD",
                            Kleur = "Zwart",
                            Merk = "Renault",
                            Type = "Kangoo"
                        },
                        new
                        {
                            Id = 88,
                            Aanschafjaar = 2017,
                            Kenteken = "EF-234-GH",
                            Kleur = "Wit",
                            Merk = "Iveco",
                            Type = "Eurocargo"
                        },
                        new
                        {
                            Id = 89,
                            Aanschafjaar = 2022,
                            Kenteken = "IJ-567-KL",
                            Kleur = "Grijs",
                            Merk = "Opel",
                            Type = "Combo"
                        },
                        new
                        {
                            Id = 90,
                            Aanschafjaar = 2021,
                            Kenteken = "MN-890-OP",
                            Kleur = "Blauw",
                            Merk = "Nissan",
                            Type = "NV200"
                        },
                        new
                        {
                            Id = 91,
                            Aanschafjaar = 2018,
                            Kenteken = "QR-123-ST",
                            Kleur = "Groen",
                            Merk = "Kia",
                            Type = "Picanto"
                        },
                        new
                        {
                            Id = 92,
                            Aanschafjaar = 2019,
                            Kenteken = "UV-456-WX",
                            Kleur = "Rood",
                            Merk = "Hyundai",
                            Type = "i30"
                        },
                        new
                        {
                            Id = 93,
                            Aanschafjaar = 2020,
                            Kenteken = "YZ-789-AB",
                            Kleur = "Zwart",
                            Merk = "Skoda",
                            Type = "Superb"
                        },
                        new
                        {
                            Id = 94,
                            Aanschafjaar = 2017,
                            Kenteken = "CD-012-EF",
                            Kleur = "Wit",
                            Merk = "Mazda",
                            Type = "6"
                        },
                        new
                        {
                            Id = 95,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-345-IJ",
                            Kleur = "Grijs",
                            Merk = "Subaru",
                            Type = "Forester"
                        },
                        new
                        {
                            Id = 96,
                            Aanschafjaar = 2019,
                            Kenteken = "KL-678-MN",
                            Kleur = "Blauw",
                            Merk = "Suzuki",
                            Type = "Swift"
                        },
                        new
                        {
                            Id = 97,
                            Aanschafjaar = 2020,
                            Kenteken = "OP-901-QR",
                            Kleur = "Groen",
                            Merk = "Volvo",
                            Type = "XC90"
                        },
                        new
                        {
                            Id = 98,
                            Aanschafjaar = 2017,
                            Kenteken = "ST-234-UV",
                            Kleur = "Rood",
                            Merk = "Mitsubishi",
                            Type = "Eclipse Cross"
                        },
                        new
                        {
                            Id = 99,
                            Aanschafjaar = 2022,
                            Kenteken = "WX-567-YZ",
                            Kleur = "Zwart",
                            Merk = "Jeep",
                            Type = "Renegade"
                        },
                        new
                        {
                            Id = 100,
                            Aanschafjaar = 2021,
                            Kenteken = "YZ-890-AB",
                            Kleur = "Zilver",
                            Merk = "Land Rover",
                            Type = "Discovery"
                        });
                });

            modelBuilder.Entity("CarenAll.Models.Camper", b =>
                {
                    b.HasBaseType("CarenAll.Models.Voertuigen");

                    b.HasDiscriminator().HasValue("Camper");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Aanschafjaar = 2018,
                            Kenteken = "AB-123-CD",
                            Kleur = "Rood",
                            Merk = "Volkswagen",
                            Type = "California"
                        },
                        new
                        {
                            Id = 102,
                            Aanschafjaar = 2019,
                            Kenteken = "EF-456-GH",
                            Kleur = "Zilver",
                            Merk = "Mercedes",
                            Type = "Marco Polo"
                        },
                        new
                        {
                            Id = 103,
                            Aanschafjaar = 2020,
                            Kenteken = "IJ-789-KL",
                            Kleur = "Blauw",
                            Merk = "Ford",
                            Type = "Transit Custom"
                        },
                        new
                        {
                            Id = 104,
                            Aanschafjaar = 2017,
                            Kenteken = "MN-012-OP",
                            Kleur = "Wit",
                            Merk = "Fiat",
                            Type = "Ducato"
                        },
                        new
                        {
                            Id = 105,
                            Aanschafjaar = 2021,
                            Kenteken = "QR-345-ST",
                            Kleur = "Grijs",
                            Merk = "Citroën",
                            Type = "Jumper"
                        },
                        new
                        {
                            Id = 106,
                            Aanschafjaar = 2016,
                            Kenteken = "UV-678-WX",
                            Kleur = "Zwart",
                            Merk = "Peugeot",
                            Type = "Boxer"
                        },
                        new
                        {
                            Id = 107,
                            Aanschafjaar = 2022,
                            Kenteken = "YZ-901-AB",
                            Kleur = "Groen",
                            Merk = "Renault",
                            Type = "Master"
                        },
                        new
                        {
                            Id = 108,
                            Aanschafjaar = 2015,
                            Kenteken = "CD-234-EF",
                            Kleur = "Blauw",
                            Merk = "Nissan",
                            Type = "NV400"
                        },
                        new
                        {
                            Id = 109,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-567-IJ",
                            Kleur = "Zilver",
                            Merk = "Opel",
                            Type = "Movano"
                        },
                        new
                        {
                            Id = 110,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Kleur = "Rood",
                            Merk = "Iveco",
                            Type = "Daily"
                        },
                        new
                        {
                            Id = 111,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-123-QR",
                            Kleur = "Wit",
                            Merk = "Volkswagen",
                            Type = "Grand California"
                        },
                        new
                        {
                            Id = 112,
                            Aanschafjaar = 2019,
                            Kenteken = "ST-456-UV",
                            Kleur = "Blauw",
                            Merk = "Mercedes",
                            Type = "Sprinter"
                        },
                        new
                        {
                            Id = 113,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-789-YZ",
                            Kleur = "Zwart",
                            Merk = "Ford",
                            Type = "Nugget"
                        },
                        new
                        {
                            Id = 114,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Kleur = "Groen",
                            Merk = "Fiat",
                            Type = "Talento"
                        },
                        new
                        {
                            Id = 115,
                            Aanschafjaar = 2018,
                            Kenteken = "EF-345-GH",
                            Kleur = "Rood",
                            Merk = "Citroën",
                            Type = "SpaceTourer"
                        },
                        new
                        {
                            Id = 116,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-678-KL",
                            Kleur = "Zwart",
                            Merk = "Peugeot",
                            Type = "Traveller"
                        },
                        new
                        {
                            Id = 117,
                            Aanschafjaar = 2020,
                            Kenteken = "MN-901-OP",
                            Kleur = "Wit",
                            Merk = "Renault",
                            Type = "Trafic"
                        },
                        new
                        {
                            Id = 118,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-234-ST",
                            Kleur = "Zilver",
                            Merk = "Nissan",
                            Type = "Primastar"
                        },
                        new
                        {
                            Id = 119,
                            Aanschafjaar = 2022,
                            Kenteken = "UV-567-WX",
                            Kleur = "Grijs",
                            Merk = "Opel",
                            Type = "Vivaro"
                        },
                        new
                        {
                            Id = 120,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-890-AB",
                            Kleur = "Zwart",
                            Merk = "Iveco",
                            Type = "Eurocargo"
                        },
                        new
                        {
                            Id = 121,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Kleur = "Blauw",
                            Merk = "Volkswagen",
                            Type = "Multivan"
                        },
                        new
                        {
                            Id = 122,
                            Aanschafjaar = 2020,
                            Kenteken = "GH-456-IJ",
                            Kleur = "Groen",
                            Merk = "Mercedes",
                            Type = "Vito"
                        },
                        new
                        {
                            Id = 123,
                            Aanschafjaar = 2017,
                            Kenteken = "KL-789-MN",
                            Kleur = "Zilver",
                            Merk = "Ford",
                            Type = "Kuga Camper"
                        },
                        new
                        {
                            Id = 124,
                            Aanschafjaar = 2018,
                            Kenteken = "OP-012-QR",
                            Kleur = "Rood",
                            Merk = "Fiat",
                            Type = "Scudo"
                        },
                        new
                        {
                            Id = 125,
                            Aanschafjaar = 2019,
                            Kenteken = "ST-345-UV",
                            Kleur = "Wit",
                            Merk = "Citroën",
                            Type = "Berlingo"
                        },
                        new
                        {
                            Id = 126,
                            Aanschafjaar = 2016,
                            Kenteken = "WX-678-YZ",
                            Kleur = "Grijs",
                            Merk = "Peugeot",
                            Type = "Expert Camper"
                        },
                        new
                        {
                            Id = 127,
                            Aanschafjaar = 2022,
                            Kenteken = "AB-901-CD",
                            Kleur = "Blauw",
                            Merk = "Renault",
                            Type = "Kangoo Camper"
                        },
                        new
                        {
                            Id = 128,
                            Aanschafjaar = 2015,
                            Kenteken = "EF-234-GH",
                            Kleur = "Zwart",
                            Merk = "Nissan",
                            Type = "Juke Camper"
                        },
                        new
                        {
                            Id = 129,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-567-IJ",
                            Kleur = "Groen",
                            Merk = "Opel",
                            Type = "Zafira Camper"
                        },
                        new
                        {
                            Id = 130,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Kleur = "Rood",
                            Merk = "Iveco",
                            Type = "Camper 2000"
                        },
                        new
                        {
                            Id = 131,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-123-QR",
                            Kleur = "Zwart",
                            Merk = "Volkswagen",
                            Type = "Kombi"
                        },
                        new
                        {
                            Id = 132,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-456-UV",
                            Kleur = "Zilver",
                            Merk = "Mercedes",
                            Type = "Sprinter XXL"
                        },
                        new
                        {
                            Id = 133,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-789-YZ",
                            Kleur = "Blauw",
                            Merk = "Ford",
                            Type = "Custom Camper"
                        },
                        new
                        {
                            Id = 134,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Kleur = "Wit",
                            Merk = "Fiat",
                            Type = "Ducato Maxi"
                        },
                        new
                        {
                            Id = 135,
                            Aanschafjaar = 2018,
                            Kenteken = "EF-345-GH",
                            Kleur = "Groen",
                            Merk = "Citroën",
                            Type = "Jumper Camper"
                        },
                        new
                        {
                            Id = 136,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-678-KL",
                            Kleur = "Zwart",
                            Merk = "Peugeot",
                            Type = "Boxer XL"
                        },
                        new
                        {
                            Id = 137,
                            Aanschafjaar = 2019,
                            Kenteken = "MN-901-OP",
                            Kleur = "Grijs",
                            Merk = "Renault",
                            Type = "Master Pro"
                        },
                        new
                        {
                            Id = 138,
                            Aanschafjaar = 2022,
                            Kenteken = "QR-234-ST",
                            Kleur = "Blauw",
                            Merk = "Nissan",
                            Type = "NV300 Camper"
                        },
                        new
                        {
                            Id = 139,
                            Aanschafjaar = 2017,
                            Kenteken = "UV-567-WX",
                            Kleur = "Zilver",
                            Merk = "Opel",
                            Type = "Vivaro XL"
                        },
                        new
                        {
                            Id = 140,
                            Aanschafjaar = 2018,
                            Kenteken = "YZ-890-AB",
                            Kleur = "Rood",
                            Merk = "Iveco",
                            Type = "Daily Pro"
                        },
                        new
                        {
                            Id = 141,
                            Aanschafjaar = 2020,
                            Kenteken = "CD-123-EF",
                            Kleur = "Groen",
                            Merk = "Volkswagen",
                            Type = "T6 California"
                        },
                        new
                        {
                            Id = 142,
                            Aanschafjaar = 2019,
                            Kenteken = "GH-456-IJ",
                            Kleur = "Zwart",
                            Merk = "Mercedes",
                            Type = "V-Class Camper"
                        },
                        new
                        {
                            Id = 143,
                            Aanschafjaar = 2022,
                            Kenteken = "KL-789-MN",
                            Kleur = "Wit",
                            Merk = "Ford",
                            Type = "Transit Nugget Plus"
                        });
                });

            modelBuilder.Entity("CarenAll.Models.Caravan", b =>
                {
                    b.HasBaseType("CarenAll.Models.Voertuigen");

                    b.HasDiscriminator().HasValue("Caravan");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Aanschafjaar = 2018,
                            Kenteken = "AB-123-CD",
                            Kleur = "Wit",
                            Merk = "Hobby",
                            Type = "De Luxe"
                        },
                        new
                        {
                            Id = 202,
                            Aanschafjaar = 2019,
                            Kenteken = "EF-456-GH",
                            Kleur = "Grijs",
                            Merk = "Fendt",
                            Type = "Bianco"
                        },
                        new
                        {
                            Id = 203,
                            Aanschafjaar = 2020,
                            Kenteken = "IJ-789-KL",
                            Kleur = "Blauw",
                            Merk = "Knaus",
                            Type = "Sport"
                        },
                        new
                        {
                            Id = 204,
                            Aanschafjaar = 2017,
                            Kenteken = "MN-012-OP",
                            Kleur = "Zilver",
                            Merk = "Adria",
                            Type = "Altea"
                        },
                        new
                        {
                            Id = 205,
                            Aanschafjaar = 2021,
                            Kenteken = "QR-345-ST",
                            Kleur = "Groen",
                            Merk = "Dethleffs",
                            Type = "Camper"
                        },
                        new
                        {
                            Id = 206,
                            Aanschafjaar = 2016,
                            Kenteken = "UV-678-WX",
                            Kleur = "Zwart",
                            Merk = "Tabbert",
                            Type = "Puccini"
                        },
                        new
                        {
                            Id = 207,
                            Aanschafjaar = 2022,
                            Kenteken = "YZ-901-AB",
                            Kleur = "Wit",
                            Merk = "Burstner",
                            Type = "Premio"
                        },
                        new
                        {
                            Id = 208,
                            Aanschafjaar = 2015,
                            Kenteken = "CD-234-EF",
                            Kleur = "Blauw",
                            Merk = "LMC",
                            Type = "Musica"
                        },
                        new
                        {
                            Id = 209,
                            Aanschafjaar = 2021,
                            Kenteken = "GH-567-IJ",
                            Kleur = "Rood",
                            Merk = "Sprite",
                            Type = "Cruzer"
                        },
                        new
                        {
                            Id = 210,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Kleur = "Grijs",
                            Merk = "Bailey",
                            Type = "Unicorn"
                        },
                        new
                        {
                            Id = 211,
                            Aanschafjaar = 2017,
                            Kenteken = "OP-123-QR",
                            Kleur = "Zilver",
                            Merk = "Lunar",
                            Type = "Clubman"
                        },
                        new
                        {
                            Id = 212,
                            Aanschafjaar = 2019,
                            Kenteken = "ST-456-UV",
                            Kleur = "Blauw",
                            Merk = "Swift",
                            Type = "Conqueror"
                        },
                        new
                        {
                            Id = 213,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-789-YZ",
                            Kleur = "Groen",
                            Merk = "Compass",
                            Type = "Casita"
                        },
                        new
                        {
                            Id = 214,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Kleur = "Rood",
                            Merk = "Coachman",
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 215,
                            Aanschafjaar = 2018,
                            Kenteken = "EF-345-GH",
                            Kleur = "Zwart",
                            Merk = "Buccaneer",
                            Type = "Commodore"
                        },
                        new
                        {
                            Id = 216,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-678-KL",
                            Kleur = "Wit",
                            Merk = "Caravelair",
                            Type = "Allegra"
                        },
                        new
                        {
                            Id = 217,
                            Aanschafjaar = 2020,
                            Kenteken = "MN-901-OP",
                            Kleur = "Zilver",
                            Merk = "Sterckeman",
                            Type = "Starlett"
                        },
                        new
                        {
                            Id = 218,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-234-ST",
                            Kleur = "Blauw",
                            Merk = "Tab",
                            Type = "320"
                        },
                        new
                        {
                            Id = 219,
                            Aanschafjaar = 2022,
                            Kenteken = "UV-567-WX",
                            Kleur = "Grijs",
                            Merk = "Eriba",
                            Type = "Touring"
                        },
                        new
                        {
                            Id = 220,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-890-AB",
                            Kleur = "Rood",
                            Merk = "Adria",
                            Type = "Action"
                        },
                        new
                        {
                            Id = 221,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Kleur = "Wit",
                            Merk = "Fendt",
                            Type = "Tendenza"
                        },
                        new
                        {
                            Id = 222,
                            Aanschafjaar = 2020,
                            Kenteken = "GH-456-IJ",
                            Kleur = "Groen",
                            Merk = "Knaus",
                            Type = "Sudwind"
                        },
                        new
                        {
                            Id = 223,
                            Aanschafjaar = 2017,
                            Kenteken = "KL-789-MN",
                            Kleur = "Zwart",
                            Merk = "Hobby",
                            Type = "Excellent"
                        },
                        new
                        {
                            Id = 224,
                            Aanschafjaar = 2019,
                            Kenteken = "OP-012-QR",
                            Kleur = "Blauw",
                            Merk = "Dethleffs",
                            Type = "Beduin"
                        },
                        new
                        {
                            Id = 225,
                            Aanschafjaar = 2021,
                            Kenteken = "ST-345-UV",
                            Kleur = "Zilver",
                            Merk = "Burstner",
                            Type = "Averso"
                        },
                        new
                        {
                            Id = 226,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-678-YZ",
                            Kleur = "Rood",
                            Merk = "LMC",
                            Type = "Vivo"
                        },
                        new
                        {
                            Id = 227,
                            Aanschafjaar = 2019,
                            Kenteken = "AB-901-CD",
                            Kleur = "Groen",
                            Merk = "Sprite",
                            Type = "Major"
                        },
                        new
                        {
                            Id = 228,
                            Aanschafjaar = 2022,
                            Kenteken = "EF-234-GH",
                            Kleur = "Wit",
                            Merk = "Bailey",
                            Type = "Phoenix"
                        },
                        new
                        {
                            Id = 229,
                            Aanschafjaar = 2017,
                            Kenteken = "GH-567-IJ",
                            Kleur = "Grijs",
                            Merk = "Lunar",
                            Type = "Delta"
                        },
                        new
                        {
                            Id = 230,
                            Aanschafjaar = 2018,
                            Kenteken = "KL-890-MN",
                            Kleur = "Zwart",
                            Merk = "Swift",
                            Type = "Elegance"
                        },
                        new
                        {
                            Id = 231,
                            Aanschafjaar = 2021,
                            Kenteken = "OP-123-QR",
                            Kleur = "Blauw",
                            Merk = "Compass",
                            Type = "Corona"
                        },
                        new
                        {
                            Id = 232,
                            Aanschafjaar = 2019,
                            Kenteken = "ST-456-UV",
                            Kleur = "Zilver",
                            Merk = "Coachman",
                            Type = "Acadia"
                        },
                        new
                        {
                            Id = 233,
                            Aanschafjaar = 2020,
                            Kenteken = "WX-789-YZ",
                            Kleur = "Rood",
                            Merk = "Buccaneer",
                            Type = "Barracuda"
                        },
                        new
                        {
                            Id = 234,
                            Aanschafjaar = 2016,
                            Kenteken = "AB-012-CD",
                            Kleur = "Groen",
                            Merk = "Caravelair",
                            Type = "Antares"
                        },
                        new
                        {
                            Id = 235,
                            Aanschafjaar = 2018,
                            Kenteken = "EF-345-GH",
                            Kleur = "Zwart",
                            Merk = "Sterckeman",
                            Type = "Evolution"
                        },
                        new
                        {
                            Id = 236,
                            Aanschafjaar = 2021,
                            Kenteken = "IJ-678-KL",
                            Kleur = "Zilver",
                            Merk = "Tab",
                            Type = "400"
                        },
                        new
                        {
                            Id = 237,
                            Aanschafjaar = 2020,
                            Kenteken = "MN-901-OP",
                            Kleur = "Blauw",
                            Merk = "Eriba",
                            Type = "Nova"
                        },
                        new
                        {
                            Id = 238,
                            Aanschafjaar = 2019,
                            Kenteken = "QR-234-ST",
                            Kleur = "Wit",
                            Merk = "Adria",
                            Type = "Adora"
                        },
                        new
                        {
                            Id = 239,
                            Aanschafjaar = 2022,
                            Kenteken = "UV-567-WX",
                            Kleur = "Zwart",
                            Merk = "Fendt",
                            Type = "Opal"
                        },
                        new
                        {
                            Id = 240,
                            Aanschafjaar = 2017,
                            Kenteken = "YZ-890-AB",
                            Kleur = "Groen",
                            Merk = "Knaus",
                            Type = "Sky Traveller"
                        },
                        new
                        {
                            Id = 241,
                            Aanschafjaar = 2018,
                            Kenteken = "CD-123-EF",
                            Kleur = "Grijs",
                            Merk = "Hobby",
                            Type = "Prestige"
                        },
                        new
                        {
                            Id = 242,
                            Aanschafjaar = 2020,
                            Kenteken = "GH-456-IJ",
                            Kleur = "Blauw",
                            Merk = "Dethleffs",
                            Type = "C'go"
                        },
                        new
                        {
                            Id = 243,
                            Aanschafjaar = 2017,
                            Kenteken = "KL-789-MN",
                            Kleur = "Rood",
                            Merk = "Burstner",
                            Type = "Premio Life"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
